
export const data = [
  {
    id: '9s41rp',
    firstName: 'Kelvin',
    lastName: 'Langosh',
    email: 'Jerod14@hotmail.com',
    phone: 8675566549,
    city: 'Coimbatore',
    country: 'India',
    postalcode: 638366,
    state: 'tamilnadu',
  },
  {
    id: '08m6rx',
    firstName: 'Molly',
    lastName: 'Purdy',
    email: 'Hugh.Dach79@hotmail.com',
    phone: 8675566577,
    city: 'Coimbatore',
    country: 'India',
    postalcode: 638316,
    state: 'tamilnadu',
  },
  {
    id: '5ymtrc',
    firstName: 'Henry',
    lastName: 'Lynch',
    email: 'Camden.Macejkovic@yahoo.com',
    phone: 8675566547,
    city: 'trichy',
    country: 'India',
    postalcode: 638344,
    state: 'tamilnadu',
  },
  {
    id: 'ek5b97',
    firstName: 'Glenda',
    lastName: 'Douglas',
    email: 'Eric0@yahoo.com',
    phone: 8675566544,
    city: 'Coimbatore',
    country: 'India',
    postalcode: 638316,
    state: 'tamilnadu',
  },
  {
    id: 'xxtydd',
    firstName: 'Leone',
    lastName: 'Williamson',
    email: 'Ericka_Mueller52@yahoo.com',
    phone: 8675566544,
    city: 'Madurai',
    country: 'India',
    postalcode: 638319,
    state: 'tamilnadu',
  },
  {
    id: 'wzxj9m',
    firstName: 'Mckenna',
    lastName: 'Friesen',
    email: 'Veda_Feeney@yahoo.com',
    phone: 8675566544,
    city: 'Chennai',
    country: 'India',
    postalcode: 600028,
    state: 'tamilnadu',
  },
  {
    id: '21dwtz',
    firstName: 'Wyman',
    lastName: 'Jast',
    email: 'Melvin.Pacocha@yahoo.com',
    phone: 8675566544,
    city: 'Mumbai',
    country: 'India',
    postalcode: 400008,
    state: 'Maharashtra',
  },
  {
    id: 'o8oe4k',
    firstName: 'Janick',
    lastName: 'Willms',
    email: 'Delfina12@gmail.com',
    phone: 8675566548,
    city: 'erode',
    country: 'India',
    postalcode: 638316,
    state: 'tamilnadu',
  },
];

export const states = [
  'Tamilnadu',
  'Maharastra',
  'Telugana',
  'Andhra',
  'kerala',
  'karnataka',
  'uttarpradhesh',
  'hariyana',
  'Delhi',
  'Pondichery',
  'Goa',
];
